# Generated by Django 4.0.3 on 2022-03-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_customer_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='optimizerderId',
            new_name='orderId',
        ),
    ]
