# Generated by Django 4.0.3 on 2022-03-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_optimizerderid_order_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
