# Generated by Django 4.0.3 on 2022-03-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
    ]
